import os
import json
from datetime import datetime, timedelta
from pathlib import Path
from odoo_helper import OdooHelper

class CEOAudit:
    """Performs a weekly audit of Odoo and Social Media to generate a CEO Briefing."""
    
    def __init__(self, vault_path: str):
        self.vault_path = Path(vault_path)
        self.briefings_dir = self.vault_path / 'Briefings'
        self.briefings_dir.mkdir(exist_ok=True)
        self.odoo = OdooHelper()

    def run_audit(self):
        print("Running Weekly Business Audit...")
        
        # 1. Get Odoo Data
        revenue_data = self.get_odoo_revenue()
        customer_count = len(self.odoo.get_customers() or [])
        
        # 2. Get Social Data (Simulated for this demo, usually reads from watcher logs)
        social_summary = {
            'facebook_posts': 3,
            'twitter_posts': 5,
            'engagement': 'High'
        }
        
        # 3. Generate Markdown
        self.generate_briefing(revenue_data, customer_count, social_summary)

    def get_odoo_revenue(self):
        """Fetch total revenue from Odoo invoices."""
        invoices = self.odoo.execute_method(
            "account.move", "search_read",
            args=[[['move_type', '=', 'out_invoice'], ['state', '=', 'posted']]],
            kwargs={"fields": ["amount_total", "invoice_date"]}
        )
        
        total = 0
        if invoices:
            total = sum(inv.get('amount_total', 0) for inv in invoices)
            
        return {
            'total_revenue': total,
            'invoice_count': len(invoices or [])
        }

    def generate_briefing(self, revenue, customers, social):
        date_str = datetime.now().strftime('%Y-%m-%d')
        filename = f"{date_str}_Monday_Briefing.md"
        
        content = f'''---
generated: {datetime.now().isoformat()}
type: ceo_briefing
---
# 📊 Monday Morning CEO Briefing ({date_str})

## 💰 Financial Overview (Odoo)
- **Total Revenue**: ${revenue['total_revenue']:,.2f}
- **Active Invoices**: {revenue['invoice_count']}
- **Total Customers**: {customers}
- **Trend**: {"✅ On Track" if revenue['total_revenue'] > 0 else "⚠️ No Revenue Recorded"}

## 📱 Social Media Summary
- **Facebook activity**: {social['facebook_posts']} updates posted this week.
- **Twitter (X) activity**: {social['twitter_posts']} posts/replies.
- **Top Engagement**: Business automation tips were well received.

## 🚀 Proactive Suggestions
1. **Odoo**: I noticed {customers} customers. Shall I draft a follow-up email for the oldest one?
2. **Social**: Engagement is high on X. We should post more AI content on Tuesday.
3. **Bottlenecks**: Response time on Facebook comments is > 12 hours. I can help automate replies.

---
*Generated by your Gold Tier AI Employee*
'''
        filepath = self.briefings_dir / filename
        filepath.write_text(content, encoding='utf-8')
        print(f"✅ Briefing generated: {filepath}")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('vault_path')
    args = parser.parse_args()
    
    audit = CEOAudit(args.vault_path)
    audit.run_audit()
