"""
AI Employee Orchestrator - Full Automation

This script automates the entire AI Employee workflow:
1. Monitors Needs_Action folder for new items
2. Processes each item automatically using Qwen Code
3. Generates Plan.md for multi-step tasks
4. Auto-approves low-risk tasks, flags high-risk for approval
5. Updates Dashboard.md automatically
6. Moves completed tasks to Done/

Usage:
    python orchestrator.py [vault_path] [check_interval_seconds]
    
Example:
    python orchestrator.py . 30
"""

import sys
import time
import logging
import subprocess
import shutil
import hashlib
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('Orchestrator')


class AutoApprovalRules:
    """Rules for automatic approval without human intervention."""
    
    # File types that can be auto-processed
    AUTO_PROCESS_TYPES = {'file_drop', 'task', 'note'}
    
    # File types that require approval
    REQUIRE_APPROVAL_TYPES = {'payment', 'email_send', 'social_post'}
    
    # Auto-approve if amount is below this threshold
    PAYMENT_AUTO_APPROVE_THRESHOLD = 100.0
    
    # Keywords that trigger approval requirement
    APPROVAL_KEYWORDS = ['approve', 'payment', 'send email', 'post', 'delete', 'cancel']
    
    @classmethod
    def can_auto_approve(cls, action_data: Dict[str, Any]) -> bool:
        """Check if an action can be auto-approved."""
        action_type = action_data.get('type', '')
        
        # Check if type requires approval
        if action_type in cls.REQUIRE_APPROVAL_TYPES:
            return False
        
        # Check for approval keywords in content
        content = action_data.get('content', '').lower()
        for keyword in cls.APPROVAL_KEYWORDS:
            if keyword in content:
                return False
        
        # Check payment amount
        if action_type == 'payment':
            amount = float(action_data.get('amount', 0))
            if amount > cls.PAYMENT_AUTO_APPROVE_THRESHOLD:
                return False
        
        return True


class DashboardUpdater:
    """Handles Dashboard.md updates."""
    
    def __init__(self, vault_path: Path):
        self.vault_path = vault_path
        self.dashboard_path = vault_path / 'Dashboard.md'
    
    def count_files(self, folder: str) -> int:
        """Count .md files in a folder."""
        folder_path = self.vault_path / folder
        if not folder_path.exists():
            return 0
        return len(list(folder_path.glob('*.md')))
    
    def get_completed_today(self) -> list:
        """Get tasks completed today."""
        done_path = self.vault_path / 'Done'
        if not done_path.exists():
            return []
        
        today = datetime.now().strftime('%Y-%m-%d')
        completed = []
        
        for f in done_path.glob('*.md'):
            try:
                content = f.read_text(encoding='utf-8')
                if today in content:
                    completed.append(f.name)
            except Exception:
                continue
        
        return completed
    
    def update(self):
        """Update Dashboard.md with current stats."""
        if not self.dashboard_path.exists():
            logger.warning('Dashboard.md not found, creating...')
            self._create_dashboard()
            return
        
        try:
            content = self.dashboard_path.read_text(encoding='utf-8')
            
            # Update counts
            pending_count = self.count_files('Needs_Action')
            approval_count = self.count_files('Pending_Approval')
            in_progress = self.count_files('In_Progress') if (self.vault_path / 'In_Progress').exists() else 0
            
            # Update Pending Tasks
            content = self._update_stat(content, 'Pending Tasks', str(pending_count))
            content = self._update_stat(content, 'Pending Approvals', str(approval_count))
            
            # Update Inbox Status section
            content = self._update_inbox_status(content, pending_count, approval_count, in_progress)
            
            # Update completed tasks
            completed = self.get_completed_today()
            content = self._update_completed_tasks(content, completed)
            
            # Update timestamp
            content = content.replace(
                '*Last generated by AI Employee*',
                f'*Last updated by Orchestrator - {datetime.now().strftime("%Y-%m-%d %H:%M")}*'
            )
            
            self.dashboard_path.write_text(content, encoding='utf-8')
            logger.info('Dashboard updated')
            
        except Exception as e:
            logger.error(f'Error updating Dashboard: {e}')
    
    def _update_stat(self, content: str, stat_name: str, value: str) -> str:
        """Update a stat value in the dashboard table."""
        lines = content.split('\n')
        for i, line in enumerate(lines):
            if stat_name in line and '|' in line:
                parts = line.split('|')
                if len(parts) >= 3:
                    parts[2] = f' {value} '
                    lines[i] = '|'.join(parts)
                    break
        return '\n'.join(lines)
    
    def _update_inbox_status(self, content: str, pending: int, approval: int, in_progress: int) -> str:
        """Update the Inbox Status section."""
        lines = content.split('\n')
        in_inbox_section = False
        
        for i, line in enumerate(lines):
            if '## 📥 Inbox Status' in line:
                in_inbox_section = True
                continue
            if in_inbox_section:
                if line.startswith('##'):
                    break
                if 'Inbox Items' in line:
                    lines[i] = f'- **Inbox Items**: {pending}'
                elif 'Needs Action' in line:
                    lines[i] = f'- **Needs Action**: {pending}'
                elif 'In Progress' in line:
                    lines[i] = f'- **In Progress**: {in_progress}'
                elif 'Pending Approval' in line:
                    lines[i] = f'- **Pending Approval**: {approval}'
        
        return '\n'.join(lines)
    
    def _update_completed_tasks(self, content: str, completed: list) -> str:
        """Update the Completed Tasks section."""
        lines = content.split('\n')
        in_completed_section = False
        new_lines = []
        skip_until_next_section = False
        
        for i, line in enumerate(lines):
            if "## ✅ Today's Completed Tasks" in line:
                in_completed_section = True
                new_lines.append(line)
                # Add completed tasks right after the header
                if completed:
                    for task in completed:
                        new_lines.append(f'- [x] {task}')
                else:
                    new_lines.append('*No tasks completed yet.*')
                continue
            
            if in_completed_section:
                if line.startswith('##') and 'Today' not in line:
                    # Reached next section
                    in_completed_section = False
                    skip_until_next_section = False
                    new_lines.append(line)
                elif line.startswith('- [x]') or '*No tasks' in line or line.strip() == '':
                    # Skip old completed tasks and empty lines in this section
                    continue
                else:
                    new_lines.append(line)
            else:
                new_lines.append(line)
        
        return '\n'.join(new_lines)
    
    def _create_dashboard(self):
        """Create a new Dashboard.md."""
        content = f'''---
last_updated: {datetime.now().isoformat()}
status: active
---

# 📊 AI Employee Dashboard

## Quick Stats

| Metric | Value |
|--------|-------|
| Pending Tasks | 0 |
| Pending Approvals | 0 |
| Bank Balance | $0.00 |
| Revenue MTD | $0.00 |

---

## 📥 Inbox Status

- **Inbox Items**: 0
- **Needs Action**: 0
- **In Progress**: 0
- **Pending Approval**: 0

---

## ✅ Today's Completed Tasks

*No tasks completed yet.*

---

## ⏳ Pending Approvals

*No pending approvals.*

---

## 📈 Active Projects

| Project | Status | Due Date |
|---------|--------|----------|
| - | - | - |

---

## 🚨 Alerts & Bottlenecks

*No alerts.*

---

## 📝 Recent Activity

*No recent activity.*

---

## 🔗 Quick Links

- [[Company_Handbook]] - Rules of Engagement
- [[Business_Goals]] - Q1 2026 Objectives
- /Inbox - Raw incoming items
- /Needs_Action - Items requiring processing
- /Done - Completed tasks
- /Pending_Approval - Awaiting approval

---

*Last updated by Orchestrator - {datetime.now().strftime("%Y-%m-%d %H:%M")}*
'''
        self.dashboard_path.write_text(content, encoding='utf-8')


class PlanGenerator:
    """Generates Plan.md for multi-step tasks."""
    
    def __init__(self, vault_path: Path):
        self.vault_path = vault_path
        self.plans_path = vault_path / 'Plans'
        self.plans_path.mkdir(exist_ok=True)
    
    def create_plan(self, task_name: str, steps: list, action_file: Path) -> Path:
        """Create a Plan.md file for a multi-step task."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        plan_name = f'PLAN_{task_name}_{timestamp}.md'
        plan_path = self.plans_path / plan_name
        
        content = f'''---
type: plan
task: {task_name}
created: {datetime.now().isoformat()}
status: in_progress
source_file: {action_file.name}
---

# Plan: {task_name}

## Steps

'''
        for i, step in enumerate(steps, 1):
            content += f'{i}. [ ] {step}\n'
        
        content += f'''
## Progress

- Started: {datetime.now().isoformat()}
- Completed: -
- Steps Done: 0/{len(steps)}

## Notes

*Add notes during execution.*

---
*Generated by AI Employee Orchestrator*
'''
        plan_path.write_text(content, encoding='utf-8')
        return plan_path


class AIEmployeeOrchestrator:
    """Main orchestrator for AI Employee automation."""
    
    def __init__(self, vault_path: Path, check_interval: int = 30):
        self.vault_path = vault_path
        self.check_interval = check_interval
        self.needs_action = vault_path / 'Needs_Action'
        self.done = vault_path / 'Done'
        self.pending_approval = vault_path / 'Pending_Approval'
        self.approved = vault_path / 'Approved'
        self.rejected = vault_path / 'Rejected'
        self.drop_folder = vault_path / 'DropFolder'
        
        # Ensure folders exist
        for folder in [self.needs_action, self.done, self.pending_approval, 
                       self.approved, self.rejected, self.drop_folder]:
            folder.mkdir(parents=True, exist_ok=True)
        
        self.dashboard = DashboardUpdater(vault_path)
        self.plan_generator = PlanGenerator(vault_path)
        self.processed_files = set()
    
    def read_action_file(self, filepath: Path) -> Dict[str, Any]:
        """Parse an action file and extract data."""
        content = filepath.read_text(encoding='utf-8')
        
        # Extract YAML frontmatter
        data = {'content': content, 'filepath': filepath}
        
        if content.startswith('---'):
            parts = content.split('---', 2)
            if len(parts) >= 3:
                yaml_content = parts[1].strip()
                for line in yaml_content.split('\n'):
                    if ':' in line:
                        key, value = line.split(':', 1)
                        data[key.strip()] = value.strip()
        
        return data
    
    def process_with_qwen(self, action_file: Path) -> tuple[bool, str, list]:
        """
        Process an action file using Qwen Code.

        Returns:
            (success, result_summary, suggested_steps)
        """
        try:
            # Read the action file
            action_data = self.read_action_file(action_file)
            action_type = action_data.get('type', 'unknown')

            logger.info(f'Processing {action_file.name} (type: {action_type})')

            # For file_drop types, check if original file exists
            original_name = action_data.get('original_name', '')
            original_path = self.drop_folder / original_name if original_name else None

            # Build prompt for Qwen Code
            prompt = self._build_processing_prompt(action_data, original_path)

            # Run Qwen Code
            result = self._run_qwen_code(prompt)

            # Handle quota exceeded - still consider it success for simple file drops
            if 'quota exceeded' in result.lower():
                # Process offline for simple file types
                if action_type == 'file_drop':
                    summary = self._process_offline(action_data, original_path)
                    return True, summary, ['File processed in offline mode']
            
            # Parse result
            success = 'error' not in result.lower() or 'offline mode' in result.lower()
            steps = self._extract_steps(result)

            return success, result, steps
            
        except Exception as e:
            logger.error(f'Error processing with Qwen: {e}')
            return False, f'Error: {e}', []
    
    def _process_offline(self, action_data: Dict[str, Any], original_path: Optional[Path]) -> str:
        """Process file offline when Qwen Code is unavailable."""
        action_type = action_data.get('type', 'unknown')
        original_name = action_data.get('original_name', '')
        
        if action_type == 'file_drop':
            # Read original file if available
            content_preview = ''
            if original_path and original_path.exists():
                try:
                    content = original_path.read_text(encoding='utf-8', errors='replace')
                    content_preview = content[:200].replace('\n', ' ')
                except Exception:
                    pass
            
            return f'File processed offline: {original_name}. Type: document. Content preview: {content_preview[:100]}...'
        
        return f'Processed offline: {action_data.get("filepath", "unknown")}'
    
    def _build_processing_prompt(self, action_data: Dict[str, Any], original_path: Optional[Path]) -> str:
        """Build prompt for Qwen Code to process the action."""
        action_type = action_data.get('type', 'unknown')
        content = action_data.get('content', '')
        
        prompt = f'''Process this AI Employee action file:

Type: {action_type}
File: {action_data.get('filepath', 'unknown')}

Content:
{content[:2000]}  # Limit content length

'''
        if original_path and original_path.exists():
            try:
                original_content = original_path.read_text(encoding='utf-8')
                prompt += f'''
Original File Content ({original_path.name}):
{original_content[:1000]}
'''
            except Exception:
                pass
        
        prompt += '''
Tasks:
1. Analyze what action is needed
2. If it's a simple file review, summarize the content
3. If it requires multiple steps, list the steps
4. Determine if this needs human approval or can be auto-approved
5. Provide a brief summary of what should be done

Output format:
- SUMMARY: [brief summary]
- STEPS: [step 1, step 2, ...] or [single action]
- APPROVAL: [AUTO or REQUIRED]
- CATEGORY: [informational, action_needed, approval_needed]
'''
        return prompt
    
    def _run_qwen_code(self, prompt: str) -> str:
        """Run Qwen Code with the given prompt."""
        try:
            import os
            # On Windows, qwen is installed as a .cmd script
            # We need to use shell=True or call it via node
            if os.name == 'nt':
                # Windows - use qwen.cmd with proper encoding
                result = subprocess.run(
                    f'qwen "{prompt.replace(chr(34), chr(34)+chr(34))}"',
                    capture_output=True,
                    text=True,
                    timeout=120,
                    cwd=str(self.vault_path),
                    shell=True,
                    encoding='utf-8',
                    errors='replace'  # Replace undecodable characters
                )
            else:
                result = subprocess.run(
                    ['qwen', prompt],
                    capture_output=True,
                    text=True,
                    timeout=120,
                    cwd=str(self.vault_path),
                    encoding='utf-8',
                    errors='replace'
                )

            # Handle None values safely
            output = result.stdout if result.stdout else ''
            if result.stderr:
                output += '\n' + result.stderr

            # Check for quota exceeded message
            if 'quota exceeded' in output.lower():
                return 'INFO: Qwen Code quota exceeded. Processing in offline mode.'

            return output

        except subprocess.TimeoutExpired:
            return 'Error: Qwen Code timed out (took more than 2 minutes)'
        except FileNotFoundError:
            return 'Error: Qwen Code not found. Processing in offline mode.'
        except Exception as e:
            return f'Error running Qwen Code: {e}'
    
    def _extract_steps(self, result: str) -> list:
        """Extract steps from Qwen Code result."""
        steps = []
        
        # Look for STEPS: line
        for line in result.split('\n'):
            if 'STEPS:' in line:
                steps_part = line.split('STEPS:')[1].strip()
                # Parse steps like "[step 1, step 2]" or "step 1, step 2"
                steps_part = steps_part.strip('[]')
                steps = [s.strip() for s in steps_part.split(',') if s.strip()]
                break
        
        return steps if steps else ['Process the file']
    
    def requires_approval(self, action_data: Dict[str, Any]) -> bool:
        """Check if action requires human approval."""
        return not AutoApprovalRules.can_auto_approve(action_data)
    
    def move_to_approval(self, action_file: Path, reason: str):
        """Move file to Pending_Approval folder."""
        # Create approval request
        approval_content = f'''---
type: approval_request
original_file: {action_file.name}
reason: {reason}
created: {datetime.now().isoformat()}
status: pending
---

# Approval Required

## Original Action
File: {action_file.name}

## Reason for Approval
{reason}

## To Approve
Move this file to /Approved folder.

## To Reject
Move this file to /Rejected folder.

---
*Created by AI Employee Orchestrator*
'''
        approval_path = self.pending_approval / f'APPROVAL_{action_file.name}'
        approval_path.write_text(approval_content, encoding='utf-8')
        
        # Move original action file to Done (approval file tracks it)
        shutil.move(str(action_file), str(self.done / action_file.name))
        
        logger.info(f'Moved to approval: {action_file.name}')
    
    def complete_task(self, action_file: Path, summary: str):
        """Mark a task as complete and move to Done."""
        # Add completion note to the file
        try:
            content = action_file.read_text(encoding='utf-8')
            content += f'\n\n---\n## Completed\n- **Completed**: {datetime.now().isoformat()}\n- **Summary**: {summary}\n'
            action_file.write_text(content, encoding='utf-8')
        except Exception as e:
            logger.warning(f'Could not update action file: {e}')
        
        # Move to Done
        dest = self.done / action_file.name
        shutil.move(str(action_file), str(dest))
        logger.info(f'Completed: {action_file.name} -> Done/')
    
    def _sync_drop_folder(self):
        """Check DropFolder for files without action files and create them."""
        if not self.drop_folder.exists():
            return
        
        # Get existing action files
        existing_actions = set()
        if self.needs_action.exists():
            for f in self.needs_action.glob('FILE_*.md'):
                content = f.read_text(encoding='utf-8', errors='ignore')
                for line in content.split('\n'):
                    if 'original_name:' in line:
                        name = line.split(':')[1].strip()
                        existing_actions.add(name)
                        break
        
        # Check for new files in DropFolder
        for file in self.drop_folder.iterdir():
            if file.is_file() and not file.name.startswith('.') and file.name not in existing_actions:
                logger.info(f'Creating action file for: {file.name}')
                self._create_action_file(file)
    
    def _create_action_file(self, filepath: Path) -> Path:
        """Create an action file for a dropped file."""
        try:
            stat = filepath.stat()
            timestamp = datetime.now().isoformat()
            file_id = hashlib.md5(f"{filepath.name}{timestamp}".encode()).hexdigest()[:8]
            file_type = filepath.suffix.lower().replace('.', '')
            
            content = f'''---
type: file_drop
category: document
original_name: {filepath.name}
file_type: {file_type}
size: {stat.st_size}
created: {timestamp}
status: pending
---

# File Drop for Processing

## File Details
- **Original Name**: {filepath.name}
- **File Type**: {file_type.upper()}
- **Size**: {stat.st_size} bytes
- **Detected**: {timestamp}

## Suggested Actions
- [ ] Review file contents
- [ ] Process or take action
- [ ] Mark as done when complete

---
*Created by AI Employee Orchestrator*
'''
            
            action_filename = f'FILE_{filepath.stem}_{file_id}.md'
            action_filepath = self.needs_action / action_filename
            action_filepath.write_text(content, encoding='utf-8')
            
            logger.info(f'Created action file: {action_filename}')
            return action_filepath
            
        except Exception as e:
            logger.error(f'Error creating action file: {e}')
            return None
    
    def process_approved_files(self):
        """Process files in Approved folder."""
        if not self.approved.exists():
            return

        # First handle email replies
        email_processor = None
        try:
            from email_reply_processor import EmailReplyProcessor
            email_processor = EmailReplyProcessor(self.vault_path)
        except ImportError:
            self.logger.warning('Email Reply Processor not available')

        for approval_file in self.approved.glob('*.md'):
            try:
                # Read approval file to find original action
                content = approval_file.read_text(encoding='utf-8')

                # Check if this is an email reply
                if 'type: approval_request' in content and 'action: email_reply' in content:
                    if email_processor:
                        logger.info(f'Processing email reply: {approval_file.name}')
                        # Extract original file name
                        original_name = None
                        for line in content.split('\n'):
                            if 'source_file:' in line:
                                original_name = line.split(':')[1].strip()
                                break
                        
                        if original_name:
                            # Process the reply
                            original_path = self.done / original_name
                            if not original_path.exists():
                                original_path = self.needs_action / original_name
                            
                            if original_path.exists():
                                reply_data = email_processor._parse_reply(
                                    original_path.read_text(encoding='utf-8')
                                )
                                if reply_data and email_processor.send_reply(reply_data):
                                    # Move to Done
                                    dest = self.done / approval_file.name
                                    shutil.move(str(approval_file), str(dest))
                                    email_processor._add_completion_note(dest)
                                    logger.info(f'Email reply sent: {original_name}')
                                    continue
                    # If we get here, move to rejected
                    shutil.move(str(approval_file), str(self.rejected / approval_file.name))
                    continue

                # Handle regular approval requests
                original_name = None
                for line in content.split('\n'):
                    if 'original_file:' in line:
                        original_name = line.split(':')[1].strip()
                        break

                if original_name:
                    # Process the approved action
                    original_path = self.done / original_name
                    if original_path.exists():
                        logger.info(f'Processing approved file: {original_name}')
                        # Re-process with approval granted
                        success, summary, _ = self.process_with_qwen(original_path)
                        if success:
                            self.complete_task(original_path, f'Approved and processed: {summary}')

                # Move approval file to Done
                shutil.move(str(approval_file), str(self.done / approval_file.name))

            except Exception as e:
                logger.error(f'Error processing approved file: {e}')
    
    def run_cycle(self):
        """Run one processing cycle."""
        logger.info('Starting processing cycle...')

        # First, process any approved files
        self.process_approved_files()
        
        # Check DropFolder for files without action files
        self._sync_drop_folder()

        # Process Needs_Action files
        if not self.needs_action.exists():
            logger.debug('Needs_Action folder empty')
            return

        for action_file in self.needs_action.glob('*.md'):
            if action_file.name in self.processed_files:
                continue  # Skip already processed files

            try:
                # Read action file
                action_data = self.read_action_file(action_file)
                
                # Check if requires approval
                if self.requires_approval(action_data):
                    logger.info(f'Requires approval: {action_file.name}')
                    self.move_to_approval(action_file, 'Action type requires human approval')
                    self.processed_files.add(action_file.name)
                    continue
                
                # Process with Qwen Code
                success, summary, steps = self.process_with_qwen(action_file)
                
                # Generate plan for multi-step tasks
                if len(steps) > 2:
                    task_name = action_data.get('original_name', action_file.stem)
                    plan_path = self.plan_generator.create_plan(task_name, steps, action_file)
                    logger.info(f'Created plan: {plan_path.name}')
                
                if success:
                    self.complete_task(action_file, summary)
                else:
                    logger.error(f'Processing failed: {summary}')
                    # Move to Done anyway with error note
                    self.complete_task(action_file, f'Error: {summary}')
                
                self.processed_files.add(action_file.name)
                
            except Exception as e:
                logger.error(f'Error processing {action_file.name}: {e}')
        
        # Update Dashboard
        self.dashboard.update()
    
    def run(self):
        """Run the orchestrator continuously."""
        logger.info('='*50)
        logger.info('🤖 AI Employee Orchestrator Started')
        logger.info(f'Vault: {self.vault_path.absolute()}')
        logger.info(f'Check interval: {self.check_interval}s')
        logger.info('='*50)
        logger.info('Drop files into DropFolder/ to begin processing')
        logger.info('Press Ctrl+C to stop\n')
        
        try:
            while True:
                self.run_cycle()
                time.sleep(self.check_interval)
        except KeyboardInterrupt:
            logger.info('\nOrchestrator stopped by user')


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        vault_path = Path('.')
    else:
        vault_path = Path(sys.argv[1])
    
    check_interval = int(sys.argv[2]) if len(sys.argv) > 2 else 30
    
    if not vault_path.exists():
        logger.error(f'Vault path does not exist: {vault_path}')
        sys.exit(1)
    
    orchestrator = AIEmployeeOrchestrator(vault_path, check_interval)
    orchestrator.run()


if __name__ == '__main__':
    main()
