"""
Plan Generator - Silver Tier Skill

Automatically generates Plan.md files for multi-step tasks.

Usage:
    python plan_generator.py <vault_path> [--all | --action-file FILE]
    python plan_generator.py <vault_path> --list
    python plan_generator.py <vault_path> --update-plan FILE --complete-step N

Example:
    python plan_generator.py ../AI_Employee_Vault --all
    python plan_generator.py ../AI_Employee_Vault --action-file FILE_project.md
"""

import sys
import logging
from pathlib import Path
from datetime import datetime
from typing import Optional

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('PlanGenerator')


class PlanGenerator:
    """
    Generates and manages Plan.md files for multi-step tasks.
    """
    
    def __init__(self, vault_path: Path):
        """
        Initialize Plan Generator.
        
        Args:
            vault_path: Path to Obsidian vault
        """
        self.vault_path = vault_path
        self.plans_path = vault_path / 'Plans'
        self.needs_action = vault_path / 'Needs_Action'
        self.done = vault_path / 'Done'
        
        # Ensure Plans folder exists
        self.plans_path.mkdir(parents=True, exist_ok=True)
    
    def create_plan(
        self,
        task_name: str,
        steps: list,
        source_file: Path,
        description: str = '',
        priority: str = 'medium',
        estimated_hours: int = None
    ) -> Path:
        """
        Create a new Plan.md file.
        
        Args:
            task_name: Name of the task/project
            steps: List of step descriptions
            source_file: Path to source action file
            description: Optional description
            priority: low, medium, high
            estimated_hours: Estimated hours to complete
            
        Returns:
            Path to created plan file
        """
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_name = self._sanitize_filename(task_name)[:30]
        
        # Generate filename
        filename = f'PLAN_{safe_name}_{timestamp}.md'
        plan_path = self.plans_path / filename
        
        # Build steps markdown
        steps_md = ''
        for i, step in enumerate(steps, 1):
            steps_md += f'{i}. [ ] {step}\n'
        
        # Build content
        content = f'''---
type: plan
task: {task_name}
created: {datetime.now().isoformat()}
status: in_progress
source_file: {source_file.name}
priority: {priority}
'''
        if estimated_hours:
            content += f'estimated_hours: {estimated_hours}\n'
        
        content += f'''---

# Plan: {task_name}

'''
        if description:
            content += f'''## Overview
{description}

'''
        
        content += '''## Steps

'''
        content += steps_md
        
        content += f'''
## Progress

- **Started**: {datetime.now().isoformat()}
- **Completed**: -
- **Steps Done**: 0/{len(steps)}
- **Next Step**: {steps[0] if steps else 'None'}

## Resources

'''
        # Add links to related files
        if (self.vault_path / 'Business_Goals.md').exists():
            content += '- [[Business_Goals]] - Related business objectives\n'
        if (self.vault_path / 'Company_Handbook.md').exists():
            content += '- [[Company_Handbook]] - Company guidelines\n'
        
        content += '''
## Notes

*Add notes during execution.*

---
*Generated by AI Employee Plan Generator*
'''
        
        plan_path.write_text(content, encoding='utf-8')
        logger.info(f'Created plan: {filename}')
        
        return plan_path
    
    def update_progress(
        self,
        plan_path: Path,
        completed_step: int = None,
        status: str = None,
        notes: str = None
    ) -> bool:
        """
        Update plan progress.
        
        Args:
            plan_path: Path to plan file
            completed_step: Step number to mark complete (1-indexed)
            status: New status (in_progress, completed, on_hold)
            notes: Additional notes to append
            
        Returns:
            True if successful
        """
        if not plan_path.exists():
            logger.error(f'Plan not found: {plan_path}')
            return False
        
        try:
            content = plan_path.read_text(encoding='utf-8')
            
            # Mark step as complete
            if completed_step:
                lines = content.split('\n')
                step_count = 0
                for i, line in enumerate(lines):
                    if line.strip().startswith('1. [ ]') or line.strip().startswith('1. [x]'):
                        step_count += 1
                        if step_count == completed_step:
                            lines[i] = line.replace('[ ]', '[x]')
                            lines[i] += f'  ✓ Completed: {datetime.now().isoformat()}'
                            logger.info(f'Marked step {completed_step} as complete')
                
                content = '\n'.join(lines)
            
            # Update status
            if status:
                content = content.replace(
                    'status: in_progress',
                    f'status: {status}'
                )
            
            # Update progress stats
            content = self._update_progress_stats(content)
            
            # Add notes
            if notes:
                content = content.replace(
                    '*Add notes during execution.*',
                    f'*Add notes during execution.*\n\n### {datetime.now().strftime("%Y-%m-%d %H:%M")}\n{notes}'
                )
            
            plan_path.write_text(content, encoding='utf-8')
            return True
            
        except Exception as e:
            logger.error(f'Error updating plan: {e}')
            return False
    
    def _update_progress_stats(self, content: str) -> str:
        """Update progress statistics in plan."""
        lines = content.split('\n')
        
        total_steps = 0
        completed_steps = 0
        
        for line in lines:
            if '[ ]' in line or '[x]' in line:
                total_steps += 1
                if '[x]' in line:
                    completed_steps += 1
        
        if total_steps > 0:
            # Update Steps Done
            for i, line in enumerate(lines):
                if '**Steps Done**:' in line:
                    lines[i] = f'- **Steps Done**: {completed_steps}/{total_steps}'
                    if completed_steps == total_steps:
                        lines[i] += ' ✅'
                    break
            
            # Update Next Step
            if completed_steps < total_steps:
                # Find next incomplete step
                step_num = 0
                for line in lines:
                    if '[ ]' in line:
                        step_num += 1
                        next_step = line.split('] ')[1] if '] ' in line else 'Unknown'
                        break
                else:
                    next_step = 'All steps complete!'
                
                for i, line in enumerate(lines):
                    if '**Next Step**:' in line:
                        lines[i] = f'- **Next Step**: {next_step}'
                        break
        
        return '\n'.join(lines)
    
    def list_plans(self, status: str = None) -> list:
        """
        List all plans.
        
        Args:
            status: Filter by status (in_progress, completed, on_hold)
            
        Returns:
            List of plan file paths
        """
        plans = []
        
        for plan_file in self.plans_path.glob('*.md'):
            if status:
                content = plan_file.read_text(encoding='utf-8')
                if f'status: {status}' in content:
                    plans.append(plan_file)
            else:
                plans.append(plan_file)
        
        return sorted(plans, key=lambda p: p.stat().st_mtime, reverse=True)
    
    def analyze_action_file(self, action_file: Path) -> dict:
        """
        Analyze an action file to determine if a plan is needed.
        
        Args:
            action_file: Path to action file
            
        Returns:
            Dict with task_name, steps, needs_plan
        """
        content = action_file.read_text(encoding='utf-8')
        
        # Extract task name from filename or content
        task_name = action_file.stem.replace('FILE_', '').replace('_', ' ').title()
        
        # Look for suggested actions
        steps = []
        in_actions = False
        for line in content.split('\n'):
            if 'Suggested Actions' in line or '## Steps' in line:
                in_actions = True
                continue
            if in_actions:
                if line.startswith('- [ ]') or line.startswith('1.'):
                    step_text = line.replace('- [ ]', '').replace('1.', '').strip()
                    if step_text:
                        steps.append(step_text)
                elif line.startswith('##') or line.startswith('---'):
                    break
        
        # Determine if plan is needed
        needs_plan = len(steps) >= 3
        
        return {
            'task_name': task_name,
            'steps': steps,
            'needs_plan': needs_plan,
            'step_count': len(steps)
        }
    
    def _sanitize_filename(self, text: str) -> str:
        """Sanitize text for use in filename."""
        invalid_chars = '<>:"/\\|?*'
        for char in invalid_chars:
            text = text.replace(char, '_')
        return text.strip().replace(' ', '_')


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python plan_generator.py <vault_path> [options]")
        print("\nOptions:")
        print("  --all                    Generate plans for all pending tasks")
        print("  --action-file FILE       Generate plan for specific action file")
        print("  --list                   List all plans")
        print("  --update-plan FILE       Update plan progress")
        print("  --complete-step N        Mark step N as complete")
        print("\nExamples:")
        print("  python plan_generator.py ../AI_Employee_Vault --all")
        print("  python plan_generator.py ../AI_Employee_Vault --action-file FILE_project.md")
        print("  python plan_generator.py ../AI_Employee_Vault --list")
        sys.exit(1)
    
    vault_path = Path(sys.argv[1])
    
    if not vault_path.exists():
        logger.error(f'Vault path does not exist: {vault_path}')
        sys.exit(1)
    
    generator = PlanGenerator(vault_path)
    
    # Parse options
    if len(sys.argv) > 2:
        if '--list' in sys.argv:
            plans = generator.list_plans()
            print(f"\n📋 Plans ({len(plans)} total):")
            for plan in plans:
                content = plan.read_text(encoding='utf-8')
                status = 'unknown'
                task = plan.stem
                for line in content.split('\n')[:10]:
                    if 'status:' in line:
                        status = line.split(':')[1].strip()
                    if 'task:' in line:
                        task = line.split(':')[1].strip()
                print(f"  - {plan.name} (Task: {task}, Status: {status})")
        
        elif '--all' in sys.argv:
            # Generate plans for all pending action files
            action_files = list(generator.needs_action.glob('*.md'))
            created = 0
            for action_file in action_files:
                analysis = generator.analyze_action_file(action_file)
                if analysis['needs_plan']:
                    generator.create_plan(
                        task_name=analysis['task_name'],
                        steps=analysis['steps'],
                        source_file=action_file
                    )
                    created += 1
            print(f"\n✅ Created {created} plans from {len(action_files)} action files")
        
        elif '--action-file' in sys.argv:
            idx = sys.argv.index('--action-file')
            if idx + 1 < len(sys.argv):
                action_file = generator.needs_action / sys.argv[idx + 1]
                if action_file.exists():
                    analysis = generator.analyze_action_file(action_file)
                    plan_path = generator.create_plan(
                        task_name=analysis['task_name'],
                        steps=analysis['steps'],
                        source_file=action_file
                    )
                    print(f"\n✅ Created plan: {plan_path.name}")
                else:
                    logger.error(f'Action file not found: {action_file}')
        
        elif '--update-plan' in sys.argv:
            idx = sys.argv.index('--update-plan')
            if idx + 1 < len(sys.argv):
                plan_file = generator.plans_path / sys.argv[idx + 1]
                completed_step = None
                if '--complete-step' in sys.argv:
                    step_idx = sys.argv.index('--complete-step')
                    if step_idx + 1 < len(sys.argv):
                        completed_step = int(sys.argv[step_idx + 1])
                
                if generator.update_progress(plan_file, completed_step=completed_step):
                    print(f"\n✅ Updated plan: {plan_file.name}")
                else:
                    logger.error('Failed to update plan')
    
    else:
        print(f"\n📁 Plans folder: {generator.plans_path}")
        plans = generator.list_plans()
        print(f"Total plans: {len(plans)}")


if __name__ == '__main__':
    main()
